{% set version = "1.13.0" %}
{% set build = 0 %}

# recipe-lint fails if mpi is undefined
{% set mpi = mpi or 'mpich' %}
{% if mpi == "mpich" %}
# prioritize mpich via build number
{% set build = build + 100 %}
{% endif %}

package:
  name: libpnetcdf
  version: {{ version }}

source:
  url: https://parallel-netcdf.github.io/Release/pnetcdf-{{ version }}.tar.gz
  sha256: aba0f1c77a51990ba359d0f6388569ff77e530ee574e40592a1e206ed9b2c491

build:
  number: {{ build }}
  skip: true  # [win]
  {% set mpi_prefix = "mpi_" + mpi %}
  # add build string so packages can depend on mpi variants dependencies:
  # `PKG_NAME * mpi_mpich_*` for mpich
  # `PKG_NAME * mpi_*` for any mpi
  string: {{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}

  run_exports:
    - {{ pin_subpackage('libpnetcdf', max_pin='x.x.x') }} {{ mpi_prefix }}_*

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - {{ mpi }}  # [mpi == 'openmpi' and build_platform != target_platform]
    - m4
    - make
  host:
    - {{ mpi }}
    - openssh  # for testing

test:
  commands:
    - pnetcdf-config --all
    - test -f ${PREFIX}/lib/pkgconfig/pnetcdf.pc
    - test -f ${PREFIX}/include/pnetcdf
    - test -f ${PREFIX}/include/pnetcdf.h
    - test -f ${PREFIX}/include/pnetcdf.mod
    - test -f ${PREFIX}/include/pnetcdf.inc
    - test ! -f ${PREFIX}/lib/libpnetcdf.a
    - test -f ${PREFIX}/lib/libpnetcdf${SHLIB_EXT}
    - pnetcdf-config --has-c++      | grep -q yes
    - pnetcdf-config --has-fortran  | grep -q yes
    # disabled for now
    # - pnetcdf-config --netcdf4      | grep -q enabled


about:
  home: https://parallel-netcdf.github.io/
  license: LicenseRef-PnetCDF
  license_file: COPYRIGHT
  summary: |
    PnetCDF is a high-performance parallel I/O library for accessing Unidata's
    NetCDF, files in classic formats, specifically the formats of CDF-1, 2, and
    5.
  dev_url: https://github.com/Parallel-NetCDF/PnetCDF

extra:
  recipe-maintainers:
    - xylar
    - zklaus
    - jedwards4b
